# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  jobs:
    - WKHTMLTOPDF_DEB=https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
    - WKHTMLTOPDF_DEB=https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb

before_install:
  - sudo apt update -y
  - sudo apt install wget -y
  - wget ${WKHTMLTOPDF_DEB}
  - sudo apt install -y ./*.deb

install:
  - pip install tox-travis

script: tox

notifications:
  email: false
