language: python
dist: xenial
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
env:
  jobs:
  - WKHTMLTOPDF_DEB=https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
  - WKHTMLTOPDF_DEB=https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
before_install:
- sudo apt update -y
- sudo apt install wget -y
- wget ${WKHTMLTOPDF_DEB}
- sudo apt install -y ./*.deb
install:
- pip install tox-travis
script: tox
notifications:
  email: false
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Cl4KP+bxePCLmfZrn6QKicH5wa8Q7LWStdi6DnjIsqm50l0/x12UxmSXp53zt/iLqc+0s51HdgTdFXoevcLldNEm6mgb+iIwc9SRyPBRufqWuRyAxT/lC8lBfTvvV5gKrcs2PKTDBvJVDP+AkQxjXcIO/uJ+VouBAHES3aGVoI0UpqgR9+PQS0ZBxfEz/3qOBN8/mbLCDvjL4C4eGXpOEFVpO5NZHMWdmyYt257H72XCLN0U2rgSWU1Ir0V9WfjHXbVly4GELNWLl+0z9nAeRd0KdqrmZ+g5FbhA5gB3jLVJBZOHDhIxSUnchgRAASHSsRhiG8CFsuKBi3CREiz9U0IAGBEQwmiORkw8Vpgb1O0GefceOTEuQ+GP9KcHqlx6st5XmrhkNsNNsbxClbeuotEqrh9Dogq6k2WmqtVVkHXD/NpyjGFrNTYIXt+ocp3Mlk1U/2Pxh5vgks5hFD2ER73HREgyuiCd+DyAnG6hpmC+OBzpG+der38vS8fIq4EEyYxrx4I2F/RO9bUVDSCxIE4y8HF8/bi+THtkJo5gaFZdkeNyhxN7b2BLYAzVZ9Up21B4/5RKSor6jxRojsMgt05HOfnjHMWV39pgL7wzjIIz83jIHsmz+0O4JSjvpUf1K3KlK8+YIW0LVDgKWufnx/9UgnlXdpA+/EPyB3n3WEU=
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
